Name: Hamid Kawsar

ID: 19-40077-1

### Descision tree classification algorithm

In [9]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer 
data = load_breast_cancer()

In [10]:
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [11]:
data_df=pd.DataFrame(data["data"],columns=data["feature_names"])

In [12]:
data_df["target"]=data["target"]

In [13]:
data_df.tail()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
564                 0.05623  ...          26.40           166.10      2027.0   
565                 0.05533  ...          38.25           155.00      1731.0   
566                 0.05648  ...          34.12           126.70      1124.0   
567                 0.07016  ...          39.42           184.60      1821.0   
568                 0.05884  ...          30.37            59.16       268.6   

     worst smoothness  worst compactness  worst concavity  \
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     worst concave points  worst symmetry  worst fractal dimension  target  
564                0.2216          0.2060                  0.07115       0  
565                0.1628          0.2572                  0.06637       0  
566                0.1418          0.2218                  0.07820       0  
567                0.2650          0.4087                  0.12400       0  
568                0.0000          0.2871                  0.07039       1  

[5 rows x 31 columns]

In [14]:
data["target_names"]

array(['malignant', 'benign'], dtype='<U9')

In [15]:
from sklearn.model_selection import train_test_split
X=data_df.drop("target",axis=1)
y=data_df["target"]
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2020)

In [16]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(criterion="entropy")

In [17]:
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.9385964912280702

In [18]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

sc.fit(x_train)

x_train_sc=sc.transform(x_train)
x_test_sc=sc.transform(x_test)
model.fit(x_train_sc,y_train)
model.score(x_test_sc,y_test)

0.9210526315789473

In [28]:
x_train_sc

array([[-0.05370575, -0.53417092, -0.01761448, ...,  0.81908207,
         1.25062232,  1.33518276],
       [ 0.87820818,  1.81956841,  0.83154698, ...,  0.6641822 ,
         0.21864042,  0.42970317],
       [-0.72514684, -1.10763578, -0.7018943 , ..., -0.68641949,
        -0.91487518, -0.11831912],
       ...,
       [ 0.38330979,  0.80851991,  0.37004618, ...,  0.54057523,
        -0.53703665, -0.89123177],
       [ 1.82169868,  0.52063594,  1.86782604, ...,  2.43223121,
         4.45975313,  1.12804691],
       [ 0.4180395 ,  0.16596289,  0.46234634, ...,  1.54977135,
         0.51325461,  1.09845607]])

In [29]:
x_train

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
215        13.86         16.93           90.96      578.9          0.10260   
460        17.08         27.15          111.20      930.9          0.09898   
540        11.54         14.44           74.65      402.9          0.09984   
270        14.29         16.82           90.30      632.6          0.06429   
357        13.87         16.21           88.52      593.7          0.08743   
..           ...           ...             ...        ...              ...   
560        14.05         27.15           91.38      600.4          0.09929   
157        16.84         19.46          108.40      880.2          0.07445   
91         15.37         22.76          100.20      728.2          0.09200   
323        20.34         21.51          135.90     1264.0          0.11700   
392        15.49         19.97          102.40      744.7          0.11600   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
215           0.15170         0.09901              0.05602         0.2106   
460           0.11100         0.10070              0.06431         0.1793   
540           0.11200         0.06737              0.02594         0.1818   
270           0.02675         0.00725              0.00625         0.1508   
357           0.05492         0.01502              0.02088         0.1424   
..                ...             ...                  ...            ...   
560           0.11260         0.04462              0.04304         0.1537   
157           0.07223         0.05150              0.02771         0.1844   
91            0.10360         0.11220              0.07483         0.1717   
323           0.18750         0.25650              0.15040         0.2569   
392           0.15620         0.18910              0.09113         0.1929   

     mean fractal dimension  ...  worst radius  worst texture  \
215                 0.06916  ...         15.75          26.93   
460                 0.06281  ...         22.96          34.49   
540                 0.06782  ...         12.26          19.68   
270                 0.05376  ...         14.91          20.65   
357                 0.05883  ...         15.11          25.58   
..                      ...  ...           ...            ...   
560                 0.06171  ...         15.30          33.17   
157                 0.05268  ...         18.22          28.07   
91                  0.06097  ...         16.43          25.84   
323                 0.06670  ...         25.30          31.86   
392                 0.06744  ...         21.20          29.41   

     worst perimeter  worst area  worst smoothness  worst compactness  \
215           104.40       750.1           0.14600            0.43700   
460           152.10      1648.0           0.16000            0.24440   
540            78.78       457.8           0.13450            0.21180   
270            94.44       684.6           0.08567            0.05036   
357            96.74       694.4           0.11530            0.10080   
..               ...         ...               ...                ...   
560           100.20       706.7           0.12410            0.22640   
157           120.30      1032.0           0.08774            0.17100   
91            107.50       830.9           0.12570            0.19970   
323           171.10      1938.0           0.15920            0.44920   
392           142.10      1359.0           0.16810            0.39130   

     worst concavity  worst concave points  worst symmetry  \
215          0.46360               0.16540          0.3630   
460          0.26390               0.15550          0.3010   
540          0.17970               0.06918          0.2329   
270          0.03866               0.03333          0.2458   
357          0.05285               0.05556          0.2362   
..               ...                   ...             ...   
560          0.13260               0.10480         

#### Predict Cancer

In [19]:
model.predict(x_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0])

In [20]:
x_test.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
236        23.21         26.97          153.50     1670.0          0.09509   
106        11.64         18.33           75.17      412.5          0.11420   
284        12.89         15.70           84.08      516.6          0.07818   
262        17.29         22.13          114.40      947.8          0.08999   
356        13.05         18.59           85.09      512.0          0.10820   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
236            0.1682         0.19500              0.12370         0.1909   
106            0.1017         0.07070              0.03485         0.1801   
284            0.0958         0.11150              0.03390         0.1432   
262            0.1273         0.09697              0.07507         0.2108   
356            0.1304         0.09603              0.05603         0.2035   

     mean fractal dimension  ...  worst radius  worst texture  \
236                 0.06309  ...         31.01          34.51   
106                 0.06520  ...         13.14          29.26   
284                 0.05935  ...         13.90          19.69   
262                 0.05464  ...         20.39          27.24   
356                 0.06501  ...         14.19          24.85   

     worst perimeter  worst area  worst smoothness  worst compactness  \
236           206.00      2944.0           0.14810             0.4126   
106            85.51       521.7           0.16880             0.2660   
284            92.12       595.6           0.09926             0.2317   
262           137.90      1295.0           0.11340             0.2867   
356            94.22       591.2           0.13430             0.2658   

     worst concavity  worst concave points  worst symmetry  \
236           0.5820                0.2593          0.3103   
106           0.2873                0.1218          0.2806   
284           0.3344                0.1017          0.1999   
262           0.2298                0.1528          0.3067   
356           0.2573                0.1258          0.3113   

     worst fractal dimension  
236                  0.08677  
106                  0.09097  
284                  0.07127  
262                  0.07484  
356                  0.08317  

[5 rows x 30 columns]

In [21]:
model.predict(x_test.head(1))

array([0])

### Descision tree Regression algorithm

In [22]:
house=pd.read_csv("bangalore house price prediction OHE-data.csv")
house

bath  balcony   price  total_sqft_int  bhk  price_per_sqft  \
0      3.0      2.0  150.00          1672.0    3     8971.291866   
1      3.0      3.0  149.00          1750.0    3     8514.285714   
2      3.0      2.0  150.00          1750.0    3     8571.428571   
3      2.0      2.0   40.00          1250.0    2     3200.000000   
4      2.0      2.0   83.00          1200.0    2     6916.666667   
...    ...      ...     ...             ...  ...             ...   
7115   3.0      2.0  325.00          2900.0    3    11206.896552   
7116   3.0      1.0   84.83          1780.0    3     4765.730337   
7117   2.0      1.0   48.00           880.0    2     5454.545455   
7118   2.0      1.0   55.00          1000.0    2     5500.000000   
7119   2.0      1.0   78.00          1400.0    3     5571.428571   

      area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                                 1                        0   
1                                 0                        1   
2                                 1                        0   
3                                 1                        0   
4                                 0                        0   
...                             ...                      ...   
7115                              1                        0   
7116                              1                        0   
7117                              0                        0   
7118                              0                        0   
7119                              0                        0   

      area_typePlot  Area  availability_Ready To Move  ...  \
0                       0                           1  ...   
1                       0                           1  ...   
2                       0                           1  ...   
3                       0                           1  ...   
4                       1                           1  ...   
...                   ...                         ...  ...   
7115                    0                           1  ...   
7116                    0                           0  ...   
7117                    1                           1  ...   
7118                    1                           0  ...   
7119                    1                           0  ...   

      location_Kalena Agrahara  location_Horamavu Agara  \
0                            0                        0   
1                            0                        0   
2                            0                        0   
3                            0                        0   
4                            0                        0   
...                        ...                      ...   
7115                         0                        0   
7116                         0                        0   
7117                         0                        0   
7118                         0                        0   
7119                         0                        0   

      location_Vidyaranyapura  location_BTM 2nd Stage  \
0                           0                       0   
1                           0                       0   
2                           0                       0   
3                           0                       0   
4                           0                       0   
...                       ...                     ...   
7115                        0                       0   
7116                        0                       0   
7117                        0                       0   
7118                        0                       0   
7119                        0                       0   

      location_Hebbal Kempapura  location_Hosur Road  \
0                             0                    0   
1                             0                    0   
2                             0                    0   
3                             0                    0   
4

In [23]:
X=house.drop("price",axis=1)
Y=house["price"]
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=200)

In [24]:
X.shape,Y.shape

((7120, 107), (7120,))

In [25]:
from sklearn.tree import DecisionTreeRegressor
model2=DecisionTreeRegressor()

model2.fit(X_train,Y_train)
model2.score(X_test,Y_test)

0.8460150540972735

In [26]:
X_test.iloc[-1,:]

bath                              3.000000
balcony                           2.000000
total_sqft_int                 1705.000000
bhk                               3.000000
price_per_sqft                 5571.847507
                                  ...     
location_Hosur Road               0.000000
location_Horamavu Banaswadi       0.000000
location_Domlur                   0.000000
location_Mahadevpura              0.000000
location_Tumkur Road              0.000000
Name: 6957, Length: 107, dtype: float64

In [27]:
model2.predict([X_test.iloc[-1,:]])

array([95.])

In [20]:
Y_test.tail()

5471     68.0
2358    125.0
542      30.0
4369    150.0
6957     95.0
Name: price, dtype: float64